language: php

php:
  - 7.4
  - nightly

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: CS_FIXER=run
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer global require fabpot/php-cs-fixer --no-update
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - make test
